app:
    queue:
        comments: comments.new
        notifications: comments.notify

spring:

    datasource:
        url: jdbc:h2:file:~/demo/data
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false
        open-in-view: false
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true

    rabbitmq:
        host: ${RMQ_HOST:localhost}
        port: ${RMQ_PORT:5672}
        username: ${RMQ_USERNAME:admin}
        password: ${RMQ_PASSWORD:password}
        template:
            reply-timeout: 5s
            receive-timeout: 5s
server:
    port: ${PORT:8080}
    error:
        include-stacktrace: never